### ISSUE TITLE
Cell phone requirements in error

### ISSUE THREAD

**Issue by ChefMongoose** [Anthrocon-Reg/anthrocon_plugin#24] opened 2015-10-24 03:00 UTC
Currently in Cell phones, an Emergency contact is listed as required, but not the Regular Cell phone number. That's the reverse of how they ought be set by default.

**Comment by kitsuta** [comment] 2015-10-24 03:01
Whoops! I just created an issue like this and fixed it. Dupe of #22.

**Closed by kitsuta** 2015-10-24 03:01 UTC
